### ISSUE TITLE
Hi Won

### ISSUE THREAD

**Issue by AutoCorrelation** [brownshit/AlphaBeta-SImulation-with-correlated-noise#1]
Long time No see

![image](https://github.com/user-attachments/assets/e7629b26-86db-4793-afd2-c92b37a93d44)

I'll take your simulation code haha
Good bye Thank you 😄

**Comment by brownshit** [comment]
내 코드 가져간 대신 대학원은 같이 다니자 ㅋㅋ

2024년 10월 23일 (수) 오전 12:16, Minjun-Chung ***@***.***>님이 작성:

**Comment by brownshit** [comment]
석박지 ㄱㄱ

2024년 10월 23일 (수) 오전 12:30, 원종찬 ***@***.***>님이 작성:

**Comment by AutoCorrelation** [comment]
### OH YeAH
